# Generated by Django 5.2.3 on 2025-06-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=255, unique=True)),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(choices=[('kshs', 'Ksh'), ('usd', 'Usd'), ('ngn', 'Ngn')], default='kshs')),
            ],
        ),
    ]
