# Generated by Django 5.2.3 on 2025-06-27 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasuryApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='amount',
            field=models.FloatField(),
        ),
    ]
