# Generated by Django 5.2.3 on 2025-06-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasuryApi', '0003_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='transaction_code',
            field=models.CharField(default='TempVal#', max_length=10, unique=True),
        ),
    ]
